document.write("<div id=\"blog_top0\"></div>");
document.write("<div id=\"blog_top\">");
document.write("<div id=\"blog_top_center\">");
document.write("<div id=\"blog_top_left\">");
document.write("<img src=\"/images/logo-blog.jpg\" onclick=\"window.location='/';\">");
document.write("</div>");
document.write("<div id=\"blog_top_right\">");
document.write("<div id=\"user_info\"> ");
document.write("</div>");
document.write("</div>");
document.write("</div>");
document.write("</div>");
